services:
  service-node:
    image: service-node:latest
    container_name: service-node
    build: .
    command: npm run dev
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - "redis"
    env_file: .env
    tty: true

  redis:
    container_name: service-node_redis
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
