services:
  node-service:
    image: node-service:latest
    container_name: node-service
    build: .
    command: npm run dev
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - "redis"
    env_file: .env
    tty: true

  redis:
    container_name: node-service_redis
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
